format = "$all"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

# default
# [[battery.display]]
# threshold = 10
# style = "bold red"

# [kubernetes]
# disabled = false

[gcloud]
disabled = true
